spin_manifest_version = 2

[application]
name = "js-component"
version = "0.1.0"
authors = ["Till Schneidereit <till@tillschneidereit.net>"]
description = ""

[[trigger.http]]
route = "/..."
component = "js-component"

[component.js-component]
source = "smoke.js.wasm"
allowed_outbound_hosts = ["https://fermyon.com/", "https://example.com:443"]
[component.js-component.build]
command = ""
watch = ["smoke.js.wasm"]
