// The constructor created by cbindgen's `derive_constructor` causes this warning.
// Gecko's various uses of cbindgen silence it, so we do, too.
#ifdef __clang__
#  pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"
#endif


#ifndef rust_uuid_bindings_h
#define rust_uuid_bindings_h

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


namespace jsuuid {


extern "C" {

/// Generate a new UUID (version 4) and return it as a C-compatible string.
/// Caller is responsible for freeing the returned string using `free_uuid`
/// function.
char *new_uuid_v4();

/// Free a C string allocated by Rust.
void free_uuid(char *s);

}  // extern "C"

}  // namespace jsuuid

#endif  // rust_uuid_bindings_h
