[book]
authors = ["StarlingMonkey Authors"]
language = "en"
multilingual = false
src = "src"
title = "StarlingMonkey Developer Documentation"
description = "Documentation for StarlingMonkey"

[preprocessor.alerts]
renderers = ["html", "linkcheck"]

[output.linkcheck]
traverse-parent-directories = true

[output.html]
git-repository-url = "https://github.com/bytecodealliance/StarlingMonkey"
edit-url-template = "https://github.com/bytecodealliance/StarlingMonkey/edit/main/docs/{path}"
default-theme = "light"
preferred-dark-theme = "navy"
copy-fonts = true
no-section-label = false
smart-punctuation = true

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
