set(WASI_SDK_VERSION 25 CACHE STRING "Version of wasi-sdk to use")

if(${HOST_OS} STREQUAL "WINDOWS")
  set(WASI_SDK_PLATFORM "x86_64")
else()
  EXECUTE_PROCESS(COMMAND uname -m OUTPUT_VARIABLE ARCH)
  if(${ARCH} MATCHES "arm64")
    set(WASI_SDK_PLATFORM "arm64")
  else()
    set(WASI_SDK_PLATFORM "x86_64")
  endif()
endif()

set(WASI_SDK_URL "https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_SDK_VERSION}/wasi-sdk-${WASI_SDK_VERSION}.0-${WASI_SDK_PLATFORM}-${HOST_OS}.tar.gz")
CPMAddPackage(NAME wasi-sdk URL ${WASI_SDK_URL})
set(WASI_SDK_PREFIX ${CPM_PACKAGE_wasi-sdk_SOURCE_DIR})
set(CMAKE_TOOLCHAIN_FILE ${CPM_PACKAGE_wasi-sdk_SOURCE_DIR}/share/cmake/wasi-sdk.cmake)
