if (DEFINED ENV{WASMTIME_FLAGS})
    set(WASMTIME_FLAGS $ENV{WASMTIME_FLAGS})
    message(STATUS "Using WASMTIME_FLAGS from environment: ${WASMTIME_FLAGS}")
endif ()

if (DEFINED ENV{WASMTIME})
    set(WASMTIME $ENV{WASMTIME})
    message(STATUS "Using WASMTIME from environment: ${WASMTIME}")
    return()
endif()

set(WASMTIME_VERSION v19.0.2)
set(WASMTIME_URL https://github.com/bytecodealliance/wasmtime/releases/download/${WASMTIME_VERSION}/wasmtime-${WASMTIME_VERSION}-${HOST_ARCH}-${HOST_OS}.tar.xz)
CPMAddPackage(NAME wasmtime URL ${WASMTIME_URL} DOWNLOAD_ONLY TRUE)
set(WASMTIME_DIR ${CPM_PACKAGE_wasmtime_SOURCE_DIR})
set(WASMTIME ${WASMTIME_DIR}/wasmtime)
