[package]
name = "generate-bindings"
build = "build.rs"
version.workspace = true
license.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib"]

[build-dependencies]
bindgen.workspace = true
